name: news_api
description: NewsAPI Flutter App - Fetch, Organize, and Stay Updated with the Latest News

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
         - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
         - asset: assets/fonts/static/Montserrat-Medium.ttf
         - asset: assets/fonts/static/Montserrat-bold.ttf
         - asset: assets/fonts/static/Montserrat-ExtraBold.ttf


